name: stockinv
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sidebar_bigeagle: ^0.2.2+1
  sidebarx: ^0.14.0
  flutter_web_data_table: ^1.0.0
  responsive_table: ^0.2.0+2
  flutter_form_builder: ^7.7.0
  flutter_datetime_picker: ^1.5.1
  date_time_picker: ^2.1.0
  intl: ^0.17.0
  bs_flutter_datatable: ^1.2.5
  http: ^0.13.5
  fluro: ^2.0.4
  bs_flutter_card: ^1.0.0
  json_path: ^0.4.2
  url_launcher: ^6.1.6
  timeago: ^3.3.0
  page_transition: ^2.0.9
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

